export const todoAppConstant = {
    GET_TODOS_REQUEST: "GET_TODOS_REQUEST",
    GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
    GET_TODOS_FAILURE: "GET_TODOS_FAILURE",
    POST_TODOS_REQUEST: "POST_TODOS_REQUEST",
    POST_TODOS_SUCCESS: "POST_TODOS_SUCCESS",
    POST_TODOS_FAILURE: "POST_TODOS_FAILURE",
    DELETE_TODOS_REQUEST: "DELETE_TODOS_REQUEST",
    DELETE_TODOS_SUCCESS: "DELETE_TODOS_SUCCESS",
    DELETE_TODOS_FAILURE: "DELETE_TODOS_FAILURE",

}